# Generated by Django 3.2.8 on 2021-10-18 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrilhaDaEvolucao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAcompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_termino', models.DateField()),
                ('observacao', models.CharField(max_length=255)),
                ('completude', models.FloatField()),
                ('id_area_programa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TrilhaDaEvolucao.areaprograma')),
                ('id_familia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TrilhaDaEvolucao.familia')),
            ],
        ),
    ]
