# Generated by Django 3.2.8 on 2021-11-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrilhaDaEvolucao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamentos',
            old_name='data_hora',
            new_name='data',
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
