# Generated by Django 3.2.8 on 2021-10-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrilhaDaEvolucao', '0002_areaacompanhamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaacompanhamento',
            name='completude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='areaacompanhamento',
            name='data_termino',
            field=models.DateField(null=True),
        ),
    ]
