# Generated by Django 3.2.8 on 2021-11-06 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrilhaDaEvolucao', '0002_auto_20211102_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamentos',
            old_name='time',
            new_name='hora',
        ),
    ]
