# Generated by Django 3.2.8 on 2021-11-11 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrilhaDaEvolucao', '0003_rename_time_agendamentos_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtuacaoParceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AreaAtuacaoVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AreaParceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('disponibilidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='AreaVoluntarioParceiro',
            new_name='AreaVoluntario',
        ),
        migrations.RenameModel(
            old_name='VoluntarioParceiro',
            new_name='Voluntario',
        ),
        migrations.DeleteModel(
            name='AreaAtuacaoVoluntarioParceiro',
        ),
        migrations.AddField(
            model_name='areaatuacaovoluntario',
            name='id_area_vol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TrilhaDaEvolucao.areavoluntario'),
        ),
        migrations.AddField(
            model_name='areaatuacaovoluntario',
            name='id_vol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TrilhaDaEvolucao.voluntario'),
        ),
        migrations.AddField(
            model_name='areaatuacaoparceiro',
            name='id_area_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TrilhaDaEvolucao.areaparceiro'),
        ),
        migrations.AddField(
            model_name='areaatuacaoparceiro',
            name='id_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TrilhaDaEvolucao.parceiro'),
        ),
    ]
