# Generated by Django 3.2.8 on 2021-10-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrilhaDaEvolucao', '0003_auto_20211018_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaacompanhamento',
            name='completude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='areaacompanhamento',
            name='data_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
